### ISSUE TITLE
请问有pytorch版本的源码嘛？

### ISSUE THREAD

**Issue by lok-18** [hanna-xu/FusionDN#3]
您好，我是一名计算机专业研究生，目前研究的研究方向就是图像融合，阅读到您这篇论文，给出的是tensorflow版的代码，请问有pytorch版本的源码嘛？如有，还请麻烦您发送到：ljw19970218@163.com。万分感谢！

**Comment by handslator** [comment]
hxd，有pytorch版本源码吗？可以发我一份吗？祝开心！
